language: ruby

matrix:
  include:
  - rvm: '3.0'
    gemfile: gemfiles/gemfile-2-3
    env: SKIP_ADAPTERS=gson,jr_jackson,nsjsonserialization
  - rvm: '3.1'
    gemfile: gemfiles/gemfile-2-3
    env: SKIP_ADAPTERS=gson,jr_jackson,nsjsonserialization
  - rvm: '3.2'
    gemfile: gemfiles/gemfile-2-3
    env: SKIP_ADAPTERS=gson,jr_jackson,nsjsonserialization
  - rvm: '3.3'
    gemfile: gemfiles/gemfile-2-3
    env: SKIP_ADAPTERS=gson,jr_jackson,nsjsonserialization
  - rvm: ruby-head
    gemfile: gemfiles/gemfile-2-3
    env: SKIP_ADAPTERS=gson,jr_jackson,nsjsonserialization
  - rvm: jruby-9000
    gemfile: gemfiles/gemfile-2-jruby
    env: SKIP_ADAPTERS=oj,yajl,jr_jackson,nsjsonserialization
  - rvm: jruby-head
    gemfile: gemfiles/gemfile-2-jruby
    env: SKIP_ADAPTERS=oj,yajl,jr_jackson,nsjsonserialization
